#!/usr/bin/env python3
"""Record weight provenance and derive the model's real memory constants.

Writes docs/model_provenance.md from the on-disk checkpoint, its SHA256SUMS file,
the resolved Hugging Face revision, and config.json. Re-runnable: it overwrites.

Why this matters (measurement_spec.md section 4): an accuracy or performance
number is only interpretable if the exact weights behind it are identifiable.
The checkpoint digest belongs next to the prompt-set digest.
"""
import datetime
import hashlib
import json
from pathlib import Path

MODEL = Path("/home/jiming/models/Qwen3-8B")
DOCS = Path.home() / "llm-quant-serve" / "docs"
REV_REF = Path.home() / ".cache/huggingface/hub/models--Qwen--Qwen3-8B/refs/main"

cfg = json.loads((MODEL / "config.json").read_text())
revision = REV_REF.read_text().strip() if REV_REF.exists() else "(unresolved)"
sums = (MODEL / "SHA256SUMS").read_text().strip().splitlines()

layers = cfg["num_hidden_layers"]
heads = cfg["num_attention_heads"]
kv_heads = cfg.get("num_key_value_heads", heads)
hidden = cfg["hidden_size"]
head_dim = hidden // heads

# Key/value cache: 2 tensors (K and V) x layers x kv_heads x head_dim x 2 bytes (bf16)
kv_bytes_per_token = 2 * layers * kv_heads * head_dim * 2
kv_gib = lambda n: n * kv_bytes_per_token / 2**30  # noqa: E731

# Weights: parameters x bytes per parameter. Parameter count read from the model card
# is approximate; the shard digests below are the authoritative artefact.
lines = []
A = lines.append

A("# Model provenance — Qwen3-8B\n")
A("> Generated by `scripts/record_provenance.py`. Regenerate after any checkpoint change.\n")
A(f"- **Recorded (UTC):** {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M}")
A("- **Repository:** `Qwen/Qwen3-8B`")
A(f"- **Resolved revision:** `{revision}`")
A("- **Retrieval endpoint:** `https://hf-mirror.com` (HF direct is unreachable from this host)")
A(f"- **Local path:** `{MODEL}`")
A("- **Precision as stored:** bfloat16\n")

A("## Architecture (from `config.json`)\n")
A("| Field | Value |")
A("|---|---|")
A(f"| architectures | `{cfg.get('architectures')}` |")
A(f"| hidden_size | {hidden} |")
A(f"| num_hidden_layers | {layers} |")
A(f"| num_attention_heads | {heads} |")
A(f"| num_key_value_heads | {kv_heads} (grouped-query attention) |")
A(f"| head_dim | {head_dim} |")
A("")

A("## Derived memory constants (used by M3 capacity analysis)\n")
A("```")
A(f"KV cache per token = 2 (K,V) x {layers} layers x {kv_heads} kv_heads x {head_dim} head_dim x 2 bytes")
A(f"                   = {kv_bytes_per_token:,} bytes = {kv_bytes_per_token/1024:.0f} KiB per token")
A("")
A(f"  8 192 tokens  -> {kv_gib(8192):.2f} GiB")
A(f" 32 768 tokens  -> {kv_gib(32768):.2f} GiB")
A("```")
A("")
A(f"BF16 weights occupy 2 bytes per parameter; at roughly 8.2 B parameters that is about "
  f"15.25 GiB, dominated by the weight tensors alone — consistent with the measured "
  f"peak of 15.28 GiB at batch 1 with 64 generated tokens.")
A("")
A("**Note on grouped-query attention:** with 8 key/value heads instead of 32, the cache is "
  "one quarter the size of the same model with full multi-head attention. Any published "
  "figure quoted for a 32-head configuration does not apply to this checkpoint.")
A("")

A("## Weight shards\n")
A("| File | SHA-256 |")
A("|---|---|")
for line in sums:
    digest, _, name = line.partition("  ")
    A(f"| `{name.strip()}` | `{digest.strip()}` |")
A("")
A("Verification command:\n")
A("```bash")
A(f"cd {MODEL} && sha256sum -c SHA256SUMS")
A("```")
A("")
A("## Fingerprint requirements\n")
A("Every file in `results/` must carry, in addition to this provenance's digest:")
A("- the resolved revision above,")
A("- `prompt_set_sha256` from `prompts/prompt_set.stats.json`,")
A("- the software fingerprint defined in `measurement_spec.md` section 4.")
A("")

DOCS.mkdir(parents=True, exist_ok=True)
out = DOCS / "model_provenance.md"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")

# A single digest over the shard digests, for compact citation in result files.
combined = hashlib.sha256("\n".join(sorted(sums)).encode()).hexdigest()
print("wrote", out)
print("revision      :", revision)
print("shards        :", len(sums))
print("kv per token  : %d bytes (%.0f KiB)" % (kv_bytes_per_token, kv_bytes_per_token / 1024))
print("kv @ 8k / 32k : %.2f / %.2f GiB" % (kv_gib(8192), kv_gib(32768)))
print("weights digest:", combined)
